config/routes.rb
Rails.application.routes.draw do
  get 'orders/new'
  devise_for :users
  resources :dogs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/", to: "dogs#welcome", as: "root"

  #display my list of dogs
  get "/mylist", to: "my_lists#index", as: "my_list"
 
  get "/orders", to: "orders#new", as: "new_order"

  get "/orders/complete", to:"orders#complete", as: "complete_order"
  
  get "/reviews/new", to: "reviews#new", as: "new_review"
  post "/reviews/", to: "reviews#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
    enum size: [:tiny_but_mighty, :pint_sized, :regular, :a_bit_extra, :upsize]
    enum gender: [:male, :female, :non_binary]
    enum age: [:puppy, :dog, :oldie_but_a_goldie]

    has_one_attached :picture
    has_many :my_lists
    has_many :reviews
    
end

app/models/my_list.rb
class MyList < ApplicationRecord
  belongs_to :user
  belongs_to :dog

  def self.contains?(current_user, dog)
    return current_user.dogs.where(id: dog.id).length > 0
  end

  def self.create_my_list(current_user, dog)
    if current_user.dogs.where(id: dog.id).length == 0
      current_user.dogs.push(dog)
      current_user.save
    end
  end

  def self.my_list_item(current_user, dog)
    return MyList.where("dog_id = ? AND user_id = ?", dog, current_user.id).first.id
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :dog
  belongs_to :user

  def self.get_average_rating(dog)
    reviews = Review.select(:rating).where(dog_id: dog.id)
    sum = 0
    reviews.each do |review|
      sum += review.rating
    end
    rating = "%.2f" % (sum.to_f / reviews.length) if sum > 0
    return rating
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :my_lists
  has_many :dogs, through: :my_lists
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  def welcome
  end
  
  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
    @reviews = @dog.reviews
    @rating = Review.get_average_rating(@dog)
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)
    @dog.picture.attach(params[:dog][:picture])
    MyList.create_my_list(current_user, @dog)
    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  def add
    dog = Dog.find(params[:id])
    current_user.dogs.push(dog)
    if current_user.save
        flash[:notice] = "Added new dog"
        redirect_to My_list__path
    else
        flash[:alert] = "Oops! There was a problem adding that dog"
        redirect_back(fallback_location: books_path)
    end
end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully removed' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dog_params
      params.require(:dog).permit(:name, :gender, :breed, :size, :age, :likes, :dislikes, :picture, :price)
    end
end

app/controllers/my_lists_controller.rb
class MyListsController < ApplicationController
    before_action :authenticate_user!

    def index
        @dogs = current_user.dogs
    end

    def edit
        @my_list = MyList.find(MyList.my_list_id(current_user,params[:id]))
    end

    def update
        @my_list = MyList.find(params[:id])
        if @my_list_item.save
            flash[:notice] = "Updated"
            redirect_to my_list_path
        end
    end


    # def destroy
    #     item_id = BookListItem.book_list_item_id(current_user, params[:id])
    #     BookListItem.destroy(item_id)
    #     flash[:notice] = "Book removed from list"
    #     redirect_to book_list_items_path
    # end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @dog = Dog.find(params[:dog_id])
    @session = Stripe::Checkout::Session.create(
    payment_method_types: ['card'],
    line_items: [{
      name: @dog.name,
      amount: (@dog.price * 100).to_i,
      currency: 'aud',
      quantity: 1,
    }],
    payment_intent_data: {
      metadata: {
        user_id: current_user.id,
        dog_id: @dog.id
      }
    },
    success_url: "#{root_url}orders/complete",
    cancel_url: "#{root_url}",
    )
  end

  def complete
  
  end
 
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def new
        @review = Review.new
        @review.dog_id = params[:dog]
    end

    def create
        dog = Dog.find(params[:review][:dog_id])
        @review = dog.reviews.new
        @review.user_id = current_user.id
        @review.rating = params[:review][:rating]
        @review.comment = params[:review][:comment]
        if @review.save
          redirect_to dog_path(dog)
        else
          flash[:alert] = "Ooops. There was a problem creating the review."
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/my_lists_helper.rb
module MyListsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/dogs/_form.html.erb
<div class="row">
<%= form_with(model: dog, local: true) do |form| %>
  <% if dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
        <% dog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.select :gender, [:male, :female, :non_binary] %>
  </div>

  <div class="field">
    <%= form.label :breed %>
    <%= form.text_field :breed %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.select :size, [:tiny_but_mighty, :pint_sized, :regular, :a_bit_extra, :upsize] %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.select :age, [:puppy, :dog, :oldie_but_a_goldie] %>
  </div>

  <div class="field">
    <%= form.label :likes %>
    <%= form.text_area :likes %>
  </div>

  <div class="field">
    <%= form.label :dislikes %>
    <%= form.text_area :dislikes %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, accept:'image/png,image/gif,image/jpeg,image/jpg' %>
  </div>

  <div class="field">
       <%= form.label :price %>
       <%= form.number_field :price, step: '0.01' %>
   </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/dogs/edit.html.erb
<h1>Editing Dog</h1>

<%= render 'form', dog: @dog %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/index.html.erb
<h1>Dogs</h1>
  <div class="box">
  <div class="card-deck">
    <% @dogs.each do |dog| %>
      <div class="card" style="min-width:250px;">
      <%= image_tag dog.picture, class:"card-img-top", width: 120  if dog.picture.attached? %>
      <div class="card-body">
      <h5 class="card-title"><%= link_to "#{dog.name.capitalize}", dog_path(dog) %></h5>
      <p class="card-text">
        <p>Gender:<%= dog.gender %></p>
        <p>Breed:<%= dog.breed %></p>
        <p>Size:<%= dog.size %></p>
    </p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Click my name for more details</small>
    </div>
  </div>   
    <% end %>
  </div>


<br>


  
  

app/views/dogs/new.html.erb
<h1>New Dog</h1>

<%= render 'form', dog: @dog %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1> <%= @dog.name %> the Wingman</h1>
</p>
<div class="container">
  <div class="row">
    <div class="col">
    <%= image_tag @dog.picture, class:'rounded float-left', width: 250 if @dog.picture.attached? %>
    </div>
  <div class="col">
  <p>
    <strong>Gender:</strong>
    <%= @dog.gender %>
  </p>

  <p>
    <strong>Breed:</strong>
    <%= @dog.breed %>
  </p>

  <p>
    <strong>Size:</strong>
    <%= @dog.size %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= @dog.age %>
  </p>

  <p>
    <strong>Likes:</strong>
    <%= @dog.likes %>
  </p>

  <p>
    <strong>Dislikes:</strong>
    <%= @dog.dislikes %>
  </p>

  <% if @dog.price %>
  <p>
    <%= number_to_currency @dog.price %> per day
      <% if user_signed_in? %>
        <%= link_to "Rent now", new_order_path(dog_id: @dog.id), class:"btn btn-dark" %>
      <% else %>
        <%= link_to "Sign in to rent me!", new_user_registration_path, class:"btn btn-dark" %>
      <% end %>
  </p>
  <% end %>
    <%= link_to 'Back', dogs_path, class:"btn btn-dark" %>
  
  </div>
  </div>

  <div>
 <h3>Reviews</h3>
 <% if user_signed_in? %>
        <%= link_to 'Add a review', new_review_path(dog: @dog), class:"btn btn-dark"%>
      <% else %>
        <%= link_to "Sign in to add a review!", new_user_registration_path, class:"btn btn-dark" %>
      <% end %>

 <p>Overall Rating: <%= @rating%> </p>

 <%if @reviews%>
   <%@reviews.each do |review|%>
     <div>
       <p class="rating"><%= "Rating: #{review.rating}"%></p>
       <p><%= review.user.email%>: <%= review.comment %></p>
     </div>
   <%end%>
 <%end%>
</div>
</div>

app/views/dogs/welcome.html.erb
<div class="container-fluid full">
  <div class="hero-text">
  <div class="white-box">
    <h1>Mans Best Wingman</h1>
    </div>
    <div class="white-button">
    <button>
      <%= link_to 'Find your new best mate', dogs_path, class:"btn btn-light" %>
    </button>
    </div>
  </div>
</div>

<!-- Section: Testimonials v.1 -->
<section class="text-center my-5 p-1">

  <!-- Section heading -->
  <h2 class="h1-responsive font-weight-bold my-5">Testimonials</h2>
  <!-- Section description -->
  <p class="dark-grey-text w-responsive mx-auto mb-5">Your best wing man, makes man's best friend your best your best asset. 
  Increase your street cred with a cute little puppy. Make the opposite sex swoon and become more popular 
  with a tiny pal. Is your tinder profile lacking something, cute puppy pics will have them swiping right in no time. Need more likes on instagram? 
  Who doesn't love a sexy pic with an adorable pal?</p>

  <!-- Grid row -->
  <div class="row">

    <!--Grid column-->
    <div class="col-lg-4 col-md-12 mb-lg-0 mb-4">
      <!--Card-->
      <div class="card testimonial-card">
        <!--Background color-->
        <div class="card-up info-color"></div>
        <!--Avatar-->
        <div class="avatar mx-auto white">
          <img src="https://mdbootstrap.com/img/Photos/Avatars/img%20(9).jpg" class="rounded-circle img-fluid">
        </div>
        <div class="card-body">
          <!--Name-->
          <h4 class="font-weight-bold mb-4">John Doe</h4>
          <hr>
          <!--Quotation-->
          <p class="dark-grey-text mt-4"><i class="fas fa-quote-left pr-2"></i>I love my best wingman, I took my puppy to the beach and my dating calander was booked out for weeks.</p>
        </div>
      </div>
      <!--Card-->
    </div>
    <!--Grid column-->

    <!--Grid column-->
    <div class="col-lg-4 col-md-6 mb-md-0 mb-4">
      <!--Card-->
      <div class="card testimonial-card">
        <!--Background color-->
        <div class="card-up blue-gradient">
        </div>
        <!--Avatar-->
        <div class="avatar mx-auto white">
          <img src="https://mdbootstrap.com/img/Photos/Avatars/img%20(20).jpg" class="rounded-circle img-fluid">
        </div>
        <div class="card-body">
          <!--Name-->
          <h4 class="font-weight-bold mb-4">Anna Aston</h4>
          <hr>
          <!--Quotation-->
          <p class="dark-grey-text mt-4"><i class="fas fa-quote-left pr-2"></i>Thanks to my best wingman I now have a million followers.</p>
        </div>
      </div>
      <!--Card-->
    </div>
    <!--Grid column-->

    <!--Grid column-->
    <div class="col-lg-4 col-md-6">
      <!--Card-->
      <div class="card testimonial-card">
        <!--Background color-->
        <div class="card-up indigo"></div>
        <!--Avatar-->
        <div class="avatar mx-auto white">
          <img src="https://mdbootstrap.com/img/Photos/Avatars/img%20(10).jpg" class="rounded-circle img-fluid">
        </div>
        <div class="card-body">
          <!--Name-->
          <h4 class="font-weight-bold mb-4">Maria Kate</h4>
          <hr>
          <!--Quotation-->
          <p class="dark-grey-text mt-4"><i class="fas fa-quote-left pr-2"></i>I can't be trusted to look after a puppy full time
          but with my best wingman now I can take the sexy but adorable pics I need which has given me insta content for months.</p>
        </div>
      </div>
      <!--Card-->
    </div>
    <!--Grid column-->

  </div>
  <!-- Grid row -->

</section>
<!-- Section: Testimonials v.1 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mans Best Wingman</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <style>
    @import url('https://fonts.googleapis.com/css?family=Julius+Sans+One|Open+Sans+Condensed:300&display=swap');
    </style>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <header class="top-nav row align-items-end bg-light">
      <%= render "shared/topnav" %>
      <%= render "shared/sidenav" %>
    </header>
      
       <script>
          function openNav() {
            document.getElementById("mySidenav").style.width = "250px";
          }

          function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
          }
      </script>
        <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; </span>
        <% if notice %>
          <p class="notice"><%= notice %></p>
        <%end%>
        <%if alert%>
        <p class="alert"><%= alert %></p>
        <% end %>
         <div id="main">
            <div class="container">
              <div class="row">
                <div class="col">
                  <%= yield %>
                </div>
              </div>
            </div>
          </div> 
  </footer>
  </body> 
</html>

app/views/my_lists/index.html.erb
<h1>My Wingman List:</h1>
<div class="row justify-content-end">
  <p><%= link_to 'Add Dog', new_dog_path, class:"btn btn-dark" %>
</div>

<%if @dogs%>
 <%@dogs.each do |dog|%>
 <div class="row">
    <div class ="col-2">
    </div>
    <div class="col-4">
        <h4><%=link_to dog.name, dog_path(dog)%></h4>
        <p><%= link_to 'Edit Dog', edit_dog_path(dog), class:"btn btn-dark" %></p>
        <p><%= link_to 'Remove Dog', dog, method: "delete", class:"btn btn-dark" %></p>
   </div>
   <div class="col-6">
        <%= image_tag dog.picture, class:'rounded float-left', width: 120 if dog.picture.attached? %>
   </div>
  </div>
 
 <%end%>
  
<%end%>

app/views/orders/complete.html.erb
<h1>Thank you for purchasing</h1>
<button> 
    <%= link_to "Go back to Home", root_path class: "btn btn-light"%>
</button>

app/views/orders/new.html.erb
<h1 class="list-item"> Your order
</h1>
<table>
<thead> 
    <tr>
     <th>Name</th>
     <th>Price</th>
   </tr>
</thead>
<tbody> 
    <tr>
        <td><%= @dog.name %></td>
        <td><%= number_to_currency @dog.price %></td>
   </tr>
 </tbody>
 </table>
<button id="pay-now">Checkout now</button>

<script src="https://js.stripe.com/v3/"></script>
<script>
 document
   .querySelector("[id='pay-now']")
   .addEventListener("click", () => {
     const stripe = Stripe(
       "<%= Rails.application.credentials.dig(:stripe, :public_key) %>"
     );
     stripe.redirectToCheckout({
       sessionId: "<%= @session.id %>"
     });
   });
</script>

app/views/reviews/new.html.erb
<h1><%= "Review for #{@review.dog.name}"%></h1>
<%=form_with model: @review do |form|%>
<%= form.hidden_field :dog_id%>
<p>
 <%= label :rating, 'Rating' %>
 <%= form.number_field :rating, min: 1, max: 5, required: true %>
</p>
<p>
 <%=label :comment, 'Comments'%>
 <%= form.text_area :comment %>
</p>
<%= form.submit "Add review", class:"btn btn-dark"%>
<p class="link item-link"><%= link_to 'Cancel', :back%>
<%end%>

app/views/shared/_sidenav.html.erb
   <div id="mySidenav" class="sidenav">
  <span class="opennav" onclick="openNav()"></span>
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    <% if user_signed_in? %>
        <p class="btn"><%= link_to 'My Dog List', my_list_path %></p>
    <% end %>
    <p class="btn"><%= link_to 'Home', root_path %></p>
    <p class="btn"><%= link_to 'View All', dogs_path %></p>
</div>

app/views/shared/_topnav.html.erb
<div class="col text-right bg-dark">
        
    <% if user_signed_in? %>
        <p class="nav-item ">
          <%= link_to 'Logout', destroy_user_session_path, method: 'delete',  class:"btn btn-dark"%>
          |
          <%= current_user.email %>
        </p>
    <% else %>
        <p class="nav-item">
          <%= link_to 'Login', new_user_session_path, class: "btn btn-dark"%>
        |
          <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-dark"%>
        </p>
    <% end %>
</div>